CREATE TABLE IF NOT EXISTS tb_cpus (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL,
    brand VARCHAR(50) NOT NULL, 
    model VARCHAR(50) NOT NULL, 
    socket VARCHAR(50) NOT NULL, 
    cores INT, 
    threads INT, 
    base_clock_speed DECIMAL(5, 2), 
    max_clock_speed DECIMAL(5, 2), 
    cache_l1 VARCHAR(50), 
    cache_l2 VARCHAR(50), 
    cache_l3 VARCHAR(50), 
    tdp_wattage_base INT NOT NULL,
    tdp_wattage_max INT, 
    integrated_graphics BOOLEAN NOT NULL,
    integrated_graphics_model VARCHAR(50), 
    photo_url VARCHAR(255),
    active BOOLEAN DEFAULT true,
    register_date DATETIME NOT NULL DEFAULT NOW(),
    FOREIGN KEY (user_id) REFERENCES tb_users(id)
);

CREATE TABLE IF NOT EXISTS rtb_cpus (
    id INT AUTO_INCREMENT PRIMARY KEY,
    cpu_id INT NOT NULL,
    user_id VARCHAR(64) NOT NULL,
    brand VARCHAR(50) NOT NULL, 
    model VARCHAR(50) NOT NULL, 
    socket VARCHAR(50) NOT NULL, 
    cores INT, 
    threads INT, 
    base_clock_speed DECIMAL(5, 2), 
    max_clock_speed DECIMAL(5, 2), 
    cache_l1 VARCHAR(50), 
    cache_l2 VARCHAR(50), 
    cache_l3 VARCHAR(50), 
    tdp_wattage_base INT NOT NULL,
    tdp_wattage_max INT, 
    integrated_graphics BOOLEAN NOT NULL,
    integrated_graphics_model VARCHAR(50), 
    photo_url VARCHAR(255),
    active BOOLEAN DEFAULT true,
    register_date DATETIME NOT NULL DEFAULT NOW(),
    FOREIGN KEY (cpu_id) REFERENCES tb_cpus(id),
    FOREIGN KEY (user_id) REFERENCES tb_users(id)
);

CREATE TRIGGER IF NOT EXISTS record_tb_cpu AFTER UPDATE ON tb_cpus FOR EACH ROW INSERT INTO rtb_cpus (
    cpu_id,
    user_id,
    brand, 
    model, 
    socket, 
    cores, 
    threads, 
    base_clock_speed, 
    max_clock_speed, 
    cache_l1, 
    cache_l2, 
    cache_l3, 
    tdp_wattage_base,
    tdp_wattage_max, 
    integrated_graphics,
    integrated_graphics_model, 
    photo_url,
    active,
    register_date
) VALUES (
    OLD.id,
    OLD.user_id,
    OLD.brand,
    OLD.model, 
    OLD.socket, 
    OLD.cores, 
    OLD.threads, 
    OLD.base_clock_speed, 
    OLD.max_clock_speed, 
    OLD.cache_l1, 
    OLD.cache_l2, 
    OLD.cache_l3, 
    OLD.tdp_wattage_base,
    OLD.tdp_wattage_max, 
    OLD.integrated_graphics,
    OLD.integrated_graphics_model, 
    OLD.photo_url,
    OLD.active,
    OLD.register_date
);